# Generated by Django 5.2.8 on 2026-02-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingplatform', '0002_testreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='lab_admin',
        ),
        migrations.RemoveField(
            model_name='labadminprofile',
            name='lab_name',
        ),
        migrations.AddField(
            model_name='labadminprofile',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='bookingplatform.lab'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labadminprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='labadminprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
