# Generated by Django 5.2.8 on 2026-02-09 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingplatform', '0003_remove_lab_lab_admin_remove_labadminprofile_lab_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labadminprofile',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_admins', to='bookingplatform.lab'),
        ),
    ]
