# Generated by Django 5.2.8 on 2026-02-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingplatform', '0010_payment_lab_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('REFUNDE', 'Refunded'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
