# Generated by Django 5.2.8 on 2026-02-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingplatform', '0012_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
