# Generated by Django 5.2.8 on 2026-02-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingplatform', '0013_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpackage',
            name='recommended_age_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
