# Generated by Django 5.2.8 on 2026-02-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingplatform', '0014_labpackage_recommended_age_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
