# Generated by Django 5.2.8 on 2026-02-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingplatform', '0015_alter_labtest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.CharField(db_collation='nocase', max_length=255, unique=True),
        ),
    ]
